name: KMeans Clustering Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        make install

    - name: Run the application
      run: |
        make run &
        sleep 10  # Sleep to ensure the server starts up properly before continuing

    - name: Verify server is running
      run: curl http://localhost:3000
